# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 5, "", "telemetry.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0ftelemetry.proto\x12\x15\x66\x65rroway.telemetry.v1"\xd9\x02\n\x10TelemetryMessage\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x12\n\nprofile_id\x18\x02 \x01(\t\x12\x12\n\nchannel_id\x18\x03 \x01(\t\x12\x17\n\x0ftimestamp_nanos\x18\x04 \x01(\x03\x12\x0c\n\x04unit\x18\x05 \x01(\t\x12/\n\x07quality\x18\x06 \x01(\x0e\x32\x1e.ferroway.telemetry.v1.Quality\x12-\n\x06source\x18\x07 \x01(\x0e\x32\x1d.ferroway.telemetry.v1.Source\x12\x11\n\tdata_type\x18\r \x01(\t\x12\x13\n\tvalue_f32\x18\x08 \x01(\x02H\x00\x12\x13\n\tvalue_f64\x18\t \x01(\x01H\x00\x12\x13\n\tvalue_i32\x18\n \x01(\x05H\x00\x12\x13\n\tvalue_i64\x18\x0b \x01(\x03H\x00\x12\x13\n\tvalue_u32\x18\x0c \x01(\rH\x00\x42\x07\n\x05value"7\n\rStreamRequest\x12\x12\n\nprofile_id\x18\x01 \x01(\t\x12\x12\n\nchannel_id\x18\x02 \x01(\t*9\n\x07Quality\x12\x08\n\x04GOOD\x10\x00\x12\x0c\n\x08\x44\x45GRADED\x10\x01\x12\t\n\x05\x46\x41ULT\x10\x02\x12\x0b\n\x07\x44ROPOUT\x10\x03*\x1e\n\x06Source\x12\x07\n\x03RAW\x10\x00\x12\x0b\n\x07\x44\x45RIVED\x10\x01\x32u\n\x0fSimulatorStream\x12\x62\n\x0fStreamTelemetry\x12$.ferroway.telemetry.v1.StreamRequest\x1a\'.ferroway.telemetry.v1.TelemetryMessage0\x01\x42\x35Z3github.com/Ferroway-Dev/ferroway/proto/telemetry/v1b\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "telemetry_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals[
        "DESCRIPTOR"
    ]._serialized_options = b"Z3github.com/Ferroway-Dev/ferroway/proto/telemetry/v1"
    _globals["_QUALITY"]._serialized_start = 447
    _globals["_QUALITY"]._serialized_end = 504
    _globals["_SOURCE"]._serialized_start = 506
    _globals["_SOURCE"]._serialized_end = 536
    _globals["_TELEMETRYMESSAGE"]._serialized_start = 43
    _globals["_TELEMETRYMESSAGE"]._serialized_end = 388
    _globals["_STREAMREQUEST"]._serialized_start = 390
    _globals["_STREAMREQUEST"]._serialized_end = 445
    _globals["_SIMULATORSTREAM"]._serialized_start = 538
    _globals["_SIMULATORSTREAM"]._serialized_end = 655
# @@protoc_insertion_point(module_scope)
